[package]
name = "simple-roguelike"
version = "0.1.0"
authors = ["Sinono3 <thesprinter79@gmail.com>"]
edition = "2018"

[dependencies]
crossterm = "0.5.0"
multi_mut = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
